/* Explicit live integration run. It creates disposable records and removes every
 * temporary identity in finally. SUPABASE_SECRET_KEY is test-process only.
 */
'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {randomUUID}=require('node:crypto');
const {createClient}=require(process.env.SUPABASE_MODULE||'@supabase/supabase-js');
for(const line of fs.readFileSync('.env.local','utf8').split(/\r?\n/)){const match=line.match(/^(SUPABASE_URL|SUPABASE_PUBLISHABLE_KEY)=(.*)$/);if(match&&!process.env[match[1]])process.env[match[1]]=match[2];}
const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_PUBLISHABLE_KEY,secret=process.env.SUPABASE_SECRET_KEY;
if(!secret)throw Error('Live integration tests require an administration credential');
const options={auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}};
const admin=createClient(url,secret,options),publicClient=createClient(url,key,options),a=createClient(url,key,options),b=createClient(url,key,options);
const users=[],results=[];let browser;
function pass(name){results.push(name);console.log('PASS',name);}
function ok(result){if(result.error)throw Error(`${result.error.code||'error'}: ${result.error.message}`);return result.data;}
function recordUser(user){if(user?.id&&!users.some(existing=>existing.id===user.id))users.push({id:user.id});return user;}
async function createVerifiedUser(label,runId,password){const email=`together-test-${runId}-${label}@example.com`;return recordUser(ok(await admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{display_name:`검증 ${label.toUpperCase()}`}})).user);}
async function signIn(client,user,password){ok(await client.auth.signInWithPassword({email:user.email,password}));}
async function assertRole(client,roles,expected){const result=await client.rpc('together_has_role',{required_roles:roles});if(result.error)throw Error(`${result.error.code||'error'}: ${result.error.message}`);assert.equal(result.data,expected);}
async function waitForAnonymous(page){await page.waitForFunction(()=>window.TogetherCloud?.user?.is_anonymous===true);return recordUser({id:await page.evaluate(()=>TogetherCloud.user.id)});}
function watchAnonymousSignup(page){return page.waitForResponse(response=>response.request().method()==='POST'&&/\/auth\/v1\/signup(?:\?|$)/.test(response.url())&&response.ok()).then(async response=>{const body=await response.json();return recordUser(body.user);});}
function hiddenOrAbsent(nodes){return nodes.every(node=>node.hidden||getComputedStyle(node).display==='none'||getComputedStyle(node).visibility==='hidden');}

(async()=>{
 const runId=randomUUID().slice(0,8),password=`Test-${randomUUID()}9!`;
 const [userA,userB]=await Promise.all([createVerifiedUser('a',runId,password),createVerifiedUser('b',runId,password)]);
 await Promise.all([signIn(a,userA,password),signIn(b,userB,password)]);
 pass('Two disposable verified email identities authenticate for ownership and operator checks');
 const lesson=require('../content/lesson.json');
 const anchor={lessonKey:`${lesson.id}@${lesson.version}`,lessonId:lesson.id,version:lesson.version,language:'ko',sectionId:'intro',sourceUrl:lesson.sourceUrl.ko,mode:'selection',quote:'연결 검증',segments:[],offsetEncoding:'UTF-16 code units',confidence:'exact'};
 const note={id:randomUUID(),owner_id:userA.id,author:'검증 A',lesson_key:anchor.lessonKey,language:'ko',body:`자동 연결 검증용 글 ${runId}`,type:'insight',scope:'class',consent:false,anchor,snapshot:null};
 ok(await a.from('together_notes').insert(note));const privateNote={...note,id:randomUUID(),scope:'private',body:`비공개 연결 검증 ${runId}`};ok(await a.from('together_notes').insert(privateNote));
 assert.equal(ok(await publicClient.from('together_notes').select('id').eq('id',note.id)).length,1);assert.equal(ok(await publicClient.from('together_notes').select('id').eq('id',privateNote.id)).length,0);assert.equal(ok(await b.from('together_notes').select('id').eq('id',privateNote.id)).length,0);
 pass('Visitors can read shared posts while private posts stay isolated to their owner');
 assert.equal(ok(await b.from('together_notes').update({body:'forbidden'}).eq('id',note.id).select('id')).length,0);assert.equal(ok(await b.from('together_notes').delete().eq('id',note.id).select('id')).length,0);assert.ok((await b.from('together_notes').insert({...note,id:randomUUID()})).error);assert.ok((await publicClient.from('together_notes').insert({...note,id:randomUUID()})).error);
 ok(await b.from('together_comments').insert({id:randomUUID(),note_id:note.id,owner_id:userB.id,author:'검증 B',body:`독립 댓글 ${runId}`}));assert.ok((await b.from('together_comments').insert({id:randomUUID(),note_id:privateNote.id,owner_id:userB.id,author:'검증 B',body:'forbidden'})).error);ok(await b.from('together_reactions').insert({note_id:note.id,owner_id:userB.id}));assert.equal((await b.from('together_reactions').insert({note_id:note.id,owner_id:userB.id})).error.code,'23505');
 pass('RLS rejects forged owners and preserves comment/reaction ownership and uniqueness');
 assert.ok((await publicClient.rpc('together_has_role',{required_roles:['teacher']})).error,'anon RPC must be rejected');const anonymousSpoof=createClient(url,key,options),anonymousSpoofData=ok(await anonymousSpoof.auth.signInAnonymously({options:{data:{role:'admin',roles:['admin','teacher'],together_staff:true}}}));recordUser(anonymousSpoofData.user);await assertRole(anonymousSpoof,['admin','editor','teacher'],false);await assertRole(b,['admin','editor','teacher'],false);ok(await b.auth.updateUser({data:{role:'admin',roles:['admin','teacher'],together_staff:true}}));await assertRole(b,['admin','editor','teacher'],false);assert.ok((await b.from('together_staff').insert({user_id:userB.id,role:'admin'})).error,'clients cannot self-grant staff');ok(await admin.from('together_staff').insert({user_id:userB.id,role:'teacher'}));await assertRole(b,['teacher'],true);await assertRole(b,['admin','editor'],false);
 pass('Anonymous callers, ordinary verified email users, metadata spoofing, and self-grants have no staff privilege; an admin temporary teacher grant works');
 const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE});const origin=process.env.TEST_SITE_URL||'http://127.0.0.1:4173';
 const readonly=await browser.newContext({viewport:{width:1440,height:1000}}),readonlyPage=await readonly.newPage(),errors=[];readonlyPage.on('pageerror',error=>errors.push(error.message));let readonlyAnonymousRequests=0;await readonlyPage.route('**/auth/v1/signup**',route=>{readonlyAnonymousRequests++;return route.continue();});await readonlyPage.goto(origin);await readonlyPage.locator('.dashboard-hero').waitFor();await readonlyPage.waitForFunction(()=>window.TogetherCloud?.ready);await readonlyPage.evaluate(()=>navigate('community'));await readonlyPage.waitForTimeout(400);
 assert.equal(await readonlyPage.evaluate(()=>TogetherCloud.user),null);assert.equal(readonlyAnonymousRequests,0);assert.equal(await readonlyPage.locator('.topbar [data-cloud="profile"]').count(),1);assert.equal(await readonlyPage.locator('#sidebar [data-cloud="account"]').count(),1);assert.equal(await readonlyPage.locator('[data-cloud="guest"],[data-cloud="signin"]').count(),0);assert.equal(await readonlyPage.locator('[data-nav="tasks"]').count(),0);assert.ok(await readonlyPage.locator('[data-nav="classroom"],[data-nav="present"],[data-nav="localprep"],[data-nav="import"]').evaluateAll(hiddenOrAbsent));
 await readonlyPage.locator('[data-cloud="profile"]').click();await readonlyPage.locator('#participantForm').waitFor();await readonlyPage.locator('#participantName').fill('화면 별명');await readonlyPage.locator('#participantForm').evaluate(form=>form.requestSubmit());await readonlyPage.waitForFunction(()=>!document.querySelector('#modal')?.open);assert.equal(await readonlyPage.evaluate(()=>TogetherCloud.user),null);
 pass('Read-only viewing and optional nickname save create no anonymous identity; public UI exposes profile and operator account controls only');
 const authFailureContext=await browser.newContext({viewport:{width:1440,height:1000}}),authFailurePage=await authFailureContext.newPage();authFailurePage.on('pageerror',error=>errors.push(error.message));await authFailurePage.goto(origin);await authFailurePage.waitForFunction(()=>TogetherCloud.ready);await authFailurePage.evaluate(id=>showThread(id),note.id);const authFailureText=`인증 실패 뒤 보존할 댓글 ${runId}`;await authFailurePage.locator('#replyText').fill(authFailureText);const eventualFailureGuest=watchAnonymousSignup(authFailurePage);let failedSignup=true;await authFailurePage.route('**/auth/v1/signup**',route=>failedSignup?route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'temporary auth failure'})}):route.continue());await authFailurePage.locator('[data-action="send-reply"]').click();await authFailurePage.waitForFunction(()=>!TogetherCloud.busy);assert.equal(await authFailurePage.evaluate(()=>TogetherCloud.user),null);assert.equal(await authFailurePage.locator('#replyText').inputValue(),authFailureText);assert.equal(await authFailurePage.locator('#authForm').count(),0);assert.equal(await authFailurePage.locator('#modal').evaluate(modal=>modal.open),true);failedSignup=false;await authFailurePage.locator('[data-action="send-reply"]').click();await eventualFailureGuest;await waitForAnonymous(authFailurePage);await authFailurePage.waitForFunction(()=>!TogetherCloud.busy&&document.querySelector('#replyText').value==='');pass('A failed first anonymous signup creates no identity and preserves the open reply and text for retry');
 const guestContext=await browser.newContext({viewport:{width:1440,height:1000}}),guestPage=await guestContext.newPage();guestPage.on('pageerror',error=>errors.push(error.message));await guestPage.goto(origin);await guestPage.waitForFunction(()=>TogetherCloud.ready);await guestPage.evaluate(id=>showThread(id),note.id);await guestPage.locator('#replyText').fill(`첫 비회원 댓글 ${runId}`);const participantFields=guestPage.locator('[data-participant-name]');assert.ok(await participantFields.count()>=1);await participantFields.first().fill('');
 await guestPage.waitForTimeout(1000);assert.equal(await guestPage.evaluate(()=>TogetherCloud.user),null);assert.equal(ok(await publicClient.from('together_comments').select('id').eq('body',`첫 비회원 댓글 ${runId}`)).length,0);await guestPage.reload();await guestPage.waitForFunction(()=>TogetherCloud.ready);await guestPage.evaluate(id=>showThread(id),note.id);assert.equal(await guestPage.locator('#replyText').inputValue(),`첫 비회원 댓글 ${runId}`);assert.match(await guestPage.locator('#replyDraftStatus').textContent(),/임시 저장됨/);pass('Unsubmitted comments autosave privately on this device, survive reload, and do not create an identity or public comment');
 let commentPosts=0;const replyIds=[];await guestPage.route('**/rest/v1/together_comments**',async route=>{if(route.request().method()!=='POST')return route.continue();commentPosts++;const payload=route.request().postDataJSON(),row=Array.isArray(payload)?payload[0]:payload;replyIds.push(row.id);if(commentPosts===1)return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'temporary test failure'})});return route.continue();});
 const createdGuest=watchAnonymousSignup(guestPage);await guestPage.locator('[data-action="send-reply"]').click();await createdGuest;await waitForAnonymous(guestPage);await guestPage.waitForFunction(()=>!TogetherCloud.busy);assert.equal(await guestPage.locator('#replyText').inputValue(),`첫 비회원 댓글 ${runId}`);assert.equal(await guestPage.locator('#replyError').isVisible(),true);assert.equal(await guestPage.locator('#authForm').count(),0);assert.equal(await guestPage.locator('#modal').evaluate(modal=>modal.open),true);await guestPage.locator('[data-action="send-reply"]').click();await guestPage.waitForFunction(()=>!TogetherCloud.busy&&document.querySelector('#replyText').value==='');assert.equal(commentPosts,2);assert.equal(replyIds[0],replyIds[1]);
 const guestId=await guestPage.evaluate(()=>TogetherCloud.user.id),savedReply=ok(await admin.from('together_comments').select('owner_id,author').eq('id',replyIds[0]).single());assert.equal(savedReply.owner_id,guestId);assert.equal(savedReply.author,'익명');pass('First guest reply creates its identity lazily; a failed write preserves the open thread, text, and stable retry identity');
 await guestPage.reload();await guestPage.waitForFunction(()=>TogetherCloud.ready&&TogetherCloud.user?.is_anonymous);assert.equal(await guestPage.evaluate(()=>TogetherCloud.user.id),guestId);assert.equal(ok(await admin.from('together_comments').select('owner_id').eq('id',replyIds[0]).single()).owner_id,guestId);pass('Refreshing retains the same guest identity and ownership of its earlier reply');
 const otherContext=await browser.newContext({viewport:{width:1440,height:1000}}),otherPage=await otherContext.newPage();otherPage.on('pageerror',error=>errors.push(error.message));await otherPage.goto(origin);await otherPage.waitForFunction(()=>TogetherCloud.ready);await otherPage.locator('#sidebar [data-cloud="account"]').click();await otherPage.locator('#authForm').waitFor();await otherPage.locator('#authEmail').fill(userB.email);await otherPage.locator('#authPassword').fill(password);await otherPage.locator('[data-cloud-submit]').click();await otherPage.waitForFunction(id=>TogetherCloud.user?.id===id&&TogetherCloud.ready,userB.id);await otherPage.evaluate(id=>showThread(id),note.id);assert.match(await otherPage.locator('#threadReplies').textContent(),/첫 비회원 댓글/);const crossReply=`다른 브라우저 댓글 ${runId}`;await otherPage.locator('#replyText').fill(crossReply);await otherPage.locator('[data-action="send-reply"]').click();await otherPage.waitForFunction(()=>!TogetherCloud.busy&&document.querySelector('#replyText').value==='');await otherPage.reload();await otherPage.waitForFunction(id=>TogetherCloud.ready&&TogetherCloud.user?.id===id,userB.id);await otherPage.evaluate(id=>showThread(id),note.id);assert.match(await otherPage.locator('#threadReplies').textContent(),new RegExp(crossReply));pass('A separate browser sees the guest reply, persists its own reply, and retains it after reload');
 const insightContext=await browser.newContext({viewport:{width:1440,height:1000}}),insightPage=await insightContext.newPage();insightPage.on('pageerror',error=>errors.push(error.message));await insightPage.goto(origin);await insightPage.waitForFunction(()=>TogetherCloud.ready);await insightPage.locator('.week-card[data-week]').first().click();await insightPage.locator('#readerCard').waitFor();await insightPage.evaluate(()=>demoTalk());await insightPage.locator('.reference-original').waitFor();assert.match(await insightPage.locator('.reference-original').getAttribute('href'),/lang=kor/);assert.equal(await insightPage.locator('.reference-original').getAttribute('target'),'_blank');await insightPage.locator('[data-v3="reference-language"][data-language="en"]').click();assert.match(await insightPage.locator('.reference-original').getAttribute('href'),/lang=eng/);await insightPage.context().route('https://www.churchofjesuschrist.org/**',route=>route.fulfill({body:'Official source navigation verified',contentType:'text/plain'}));const sourcePopup=insightPage.waitForEvent('popup');await insightPage.locator('.reference-original').click();const sourcePage=await sourcePopup;await sourcePage.waitForLoadState();assert.match(sourcePage.url(),/churchofjesuschrist\.org/);await sourcePage.close();await insightPage.locator('[data-enhance="ref-select-verse"]').first().click();await insightPage.locator('[data-enhance="ref-insight"]').click();const insightBody=`첫 비회원 인사이트 ${runId}`;await insightPage.locator('#insightText').fill(insightBody);await insightPage.waitForFunction(()=>!composer.capturePending);const insightGuest=watchAnonymousSignup(insightPage);await insightPage.locator('[data-enhance="share-insight"]').click();await insightGuest;await waitForAnonymous(insightPage);await insightPage.waitForFunction(()=>!TogetherCloud.busy&&!document.querySelector('#modal')?.open);assert.equal(await insightPage.locator('#authForm').count(),0);const insight=ok(await admin.from('together_notes').select('id,owner_id,anchor').eq('body',insightBody).single());assert.equal(insight.owner_id,await insightPage.evaluate(()=>TogetherCloud.user.id));assert.equal(insight.anchor.lessonKey,anchor.lessonKey);pass('First guest insight survives the auth callback and saves its source anchor without an auth modal; its official source opens in the selected language');
 const likeContext=await browser.newContext({viewport:{width:1440,height:1000}}),likePage=await likeContext.newPage();likePage.on('pageerror',error=>errors.push(error.message));let signupCalls=0;await likePage.route('**/auth/v1/signup**',route=>{signupCalls++;return route.continue();});await likePage.goto(origin);await likePage.waitForFunction(()=>TogetherCloud.ready);const likeGuest=watchAnonymousSignup(likePage);await likePage.evaluate(async id=>Promise.all([toggleLike(id),toggleLike(id)]),note.id);await likeGuest;await waitForAnonymous(likePage);assert.equal(signupCalls,1);const likerId=await likePage.evaluate(()=>TogetherCloud.user.id);assert.equal(ok(await admin.from('together_reactions').select('owner_id').eq('note_id',note.id).eq('owner_id',likerId)).length,1);pass('First reaction is single-flight: one anonymous signup and one owned reaction');
 await readonlyPage.locator('#sidebar [data-cloud="account"]').click();await readonlyPage.locator('#authForm').waitFor();await readonlyPage.locator('#authEmail').fill(userA.email);await readonlyPage.locator('#authPassword').fill(password);await readonlyPage.locator('[data-cloud-submit]').click();await readonlyPage.waitForFunction(id=>TogetherCloud.user?.id===id&&TogetherCloud.ready,userA.id);await readonlyPage.evaluate(()=>TogetherCloud.sync({force:true}));assert.equal(await readonlyPage.evaluate(id=>state.notes.some(note=>note.id===id&&note.scope==='private'&&note.owner==='me'),privateNote.id),true);await readonlyPage.locator('#sidebar [data-cloud="account"]').click();await readonlyPage.locator('[data-cloud="signout"]').click();await readonlyPage.waitForFunction(()=>!TogetherCloud.user&&TogetherCloud.ready);await readonlyPage.locator('#sidebar [data-cloud="account"]').click();await readonlyPage.locator('#authEmail').fill(userB.email);await readonlyPage.locator('#authPassword').fill(password);await readonlyPage.locator('[data-cloud-submit]').click();await readonlyPage.waitForFunction(id=>TogetherCloud.user?.id===id&&TogetherCloud.ready,userB.id);assert.equal(await readonlyPage.evaluate(id=>state.notes.some(note=>note.id===id),privateNote.id),false);await readonlyPage.waitForFunction(()=>TogetherAccess.role==='teacher');assert.equal(await readonlyPage.evaluate(()=>TogetherAccess.can('present')),true);assert.equal(await readonlyPage.evaluate(()=>TogetherAccess.can('content')),false);pass('Switching accounts in one browser purges prior private records and loads only server-backed staff capability');
 const recovery=ok(await admin.auth.admin.generateLink({type:'recovery',email:userB.email,options:{redirectTo:`${origin}/?auth=reset`}}));const recoveryContext=await browser.newContext(),recoveryPage=await recoveryContext.newPage();recoveryPage.on('pageerror',error=>errors.push(error.message));await recoveryPage.goto(recovery.properties.action_link);await recoveryPage.locator('#authForm[data-mode="new-password"]').waitFor();const newPassword=`Changed-${randomUUID()}9!`;await recoveryPage.locator('#authPassword').fill(newPassword);await recoveryPage.locator('#authConfirm').fill(newPassword);await recoveryPage.locator('[data-cloud-submit]').click();await recoveryPage.locator('#authForm[data-mode="signin"]').waitFor();const resetClient=createClient(url,key,options);assert.ok((await resetClient.auth.signInWithPassword({email:userB.email,password})).error);ok(await resetClient.auth.signInWithPassword({email:userB.email,password:newPassword}));pass('The separate operator account supports staff capability checks and password recovery');
 assert.deepEqual(errors,[]);pass('Guest and operator browser workflows have no runtime errors');fs.mkdirSync('evidence',{recursive:true});fs.writeFileSync('evidence/cloud-verification.json',JSON.stringify({testedAt:new Date().toISOString(),results,emailDeliveryTested:false,temporaryUsersRemoved:'See successful cleanup output'},null,2));console.log('RESULT',results.length,'checks passed');
})().catch(error=>{console.error('FAIL',String(error.message).replace(/https?:\/\/\S+/g,'[URL omitted]'));process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();let removed=0;for(const user of users){await admin.from('together_staff').delete().eq('user_id',user.id);const {error}=await admin.auth.admin.deleteUser(user.id);if(error){console.error('Temporary identity cleanup failed');process.exitCode=1;}else removed++;}console.log('Cleanup:',removed,'temporary identities removed');});
