/* Public ward calendar. Database policies enforce organization-scoped editing. */
'use strict';
(()=>{
 const M=window.TogetherCalendarModel,BUCKET='together-event-posters';
 const today=M.dayKey(new Date()),C={items:[],current:null,slug:null,loading:false,error:'',missing:false,year:Number(today.slice(0,4)),month:Number(today.slice(5,7))-1,day:Number(today.slice(-2)),layout:innerWidth<=760?'list':'month',organizations:[],includeAll:true,query:'',generation:0,editor:null,busy:false};
 const posters=new Map();let identity=window.TogetherCloud?.user?.id||null;
 const api=window.TogetherCalendar={html,refresh,open,showCollection,showEditor,afterRender,suspend,getState:()=>C};
 const client=()=>window.TogetherCloud?.client;
 const me=()=>window.TogetherCloud?.user;
 const canEdit=row=>window.TogetherAccess?.canManageEvent?.(row)===true;
 const canCreate=()=>window.TogetherAccess?.can?.('events')===true;
 const label=id=>{const org=M.ORGANIZATIONS.find(x=>x[0]===id);return org?org[lang()==='ko'?1:2]:id;};
 const button=(action,text,primary=false,extraClass='')=>`<button type="button" class="btn${primary?' primary':''}${extraClass?' '+extraClass:''}" data-calendar-action="${action}">${text}</button>`;
 const dayString=day=>`${C.year}-${String(C.month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;
 const dateLabel=value=>new Intl.DateTimeFormat(lang()==='ko'?'ko-KR':'en-US',{timeZone:M.ZONE,month:'long',day:'numeric',weekday:'short'}).format(new Date(value));
 const statusName=status=>({draft:E('임시 저장','Draft'),published:E('게시됨','Published'),cancelled:E('취소됨','Cancelled')})[status]||'';
 const visible=row=>row&&M.canView(row,canEdit(row));
 const tags=row=>row.organizations.map(o=>`<span class="calendar-tag org-${esc(o)}">${esc(label(o))}</span>`).join('');
 const message=error=>error?.code==='42501'?E('이 조직의 일정을 관리할 권한이 없습니다.','You do not have permission to manage this organization’s events.'):error?.message==='conflict'?E('다른 담당자가 이 일정을 변경했습니다. 입력 내용은 유지했습니다. 목록에서 최신 내용을 확인한 뒤 다시 수정해 주세요.','Another editor changed this event. Your input is kept. Review the latest event before editing again.'):E('연결을 확인하고 다시 시도해 주세요. 입력한 내용은 그대로 남아 있습니다.','Check your connection and try again. Your input has been kept.');
 try{const pref=JSON.parse(localStorage.getItem('together-calendar-preferences')||'{}');C.organizations=Array.isArray(pref.organizations)?pref.organizations.filter(x=>M.ORGANIZATIONS.some(o=>o[0]===x)):[];C.includeAll=pref.includeAll!==false;if(['month','list'].includes(pref.layout))C.layout=pref.layout;}catch{}
 function preferences(){try{localStorage.setItem('together-calendar-preferences',JSON.stringify({organizations:C.organizations,includeAll:C.includeAll,layout:C.layout}));}catch{}}
 function filtered(){return M.filterEvents(C.items.filter(visible),C);}
 function html(){
  if(C.slug)return C.loading?loading():C.current&&visible(C.current)?detail(C.current):emptyState(C.error||E('일정을 찾을 수 없거나 공개되지 않았습니다.','This event is unavailable or has not been published.'),true);
  const rows=filtered();
  return `<main class="workspace calendar-workspace"><div class="page-intro calendar-intro"><div><div class="eyebrow">OUR WARD · TOGETHER</div><h1>${E('우리 와드, 한눈에.','Our ward, at a glance.')}</h1><p>${E('다가오는 만남을 확인하고 함께 준비해요.','See what is coming up and prepare together.')}</p></div>${canCreate()?button('new',icon('plus')+E('일정 등록','New event'),true):''}</div>${filtersHTML()}<div class="calendar-toolbar"><div class="calendar-month"><button class="calendar-icon-button" data-calendar-action="previous" aria-label="${E('이전 달','Previous month')}">${icon('back')}</button><h2>${C.year}${E('년 ', ' / ')}${C.month+1}${E('월','')}</h2><button class="calendar-icon-button" data-calendar-action="next" aria-label="${E('다음 달','Next month')}">${icon('arrow')}</button>${button('today',E('오늘','Today'))}</div><div class="calendar-view-toggle"><button data-calendar-layout="month" aria-pressed="${C.layout==='month'}">${E('달력','Month')}</button><button data-calendar-layout="list" aria-pressed="${C.layout==='list'}">${E('목록','List')}</button></div></div><p class="calendar-summary">${E('한국 시간 (UTC+9)','Korea time (UTC+9)')} · ${rows.length}${E('개의 일정',' events')}${canCreate()?' · '+E('임시 저장은 담당자에게만 표시','Drafts are visible only to assigned editors'):''}</p>${C.loading?loadingContent():C.error?errorContent(C.error):C.layout==='month'?monthHTML(rows):rows.length?`<div class="calendar-list">${rows.map(eventRow).join('')}</div>`:emptyContent()}</main>`;
 }
 function filtersHTML(){return `<section class="calendar-filters" aria-label="${E('일정 필터','Event filters')}"><div class="calendar-filter-chips"><span>${E('조직별로 보기','Organizations')}</span><button class="calendar-chip" data-calendar-org="all-organizations" aria-pressed="${!C.organizations.length}">${E('전체','All')}</button>${M.ORGANIZATIONS.map(([id])=>`<button class="calendar-chip" data-calendar-org="${id}" aria-pressed="${C.organizations.includes(id)}"><span class="calendar-dot org-${id}"></span>${esc(label(id))}</button>`).join('')}</div><div class="calendar-filter-extra"><label class="calendar-check"><input id="calendarIncludeAll" type="checkbox" ${C.includeAll?'checked':''}>${E('전 회원 일정 함께 보기','Include all-member events')}</label><label class="calendar-search">${icon('search','small')}<input id="calendarSearch" type="search" value="${esc(C.query)}" placeholder="${E('제목 또는 장소 검색','Search title or location')}" aria-label="${E('일정 검색','Search events')}"></label></div></section>`;}
 function eventRow(row){const date=M.dayKey(row.starts_at);return `<button class="calendar-event-row" data-event-open="${esc(row.slug)}"><span class="calendar-date-tile"><strong>${Number(date.slice(-2))}</strong><small>${new Intl.DateTimeFormat(lang()==='ko'?'ko-KR':'en',{timeZone:M.ZONE,weekday:'short'}).format(new Date(row.starts_at))}</small></span><span class="calendar-event-summary"><span>${tags(row)}${row.status!=='published'?`<span class="calendar-status ${row.status}">${statusName(row.status)}</span>`:''}</span><strong class="${row.status==='cancelled'?'is-cancelled':''}">${esc(row.title)}</strong><small>${esc(timeRange(row))} · ${esc(row.location)}</small></span>${icon('arrow','small')}</button>`;}
 function timeRange(row){const start=M.dayKey(row.starts_at),end=M.dayKey(row.ends_at);return `${M.timeKey(row.starts_at)} – ${start===end?'':end+' '}${M.timeKey(row.ends_at)}`;}
 function monthHTML(rows){const first=new Date(C.year,C.month,1).getDay(),length=new Date(C.year,C.month+1,0).getDate(),cells=Math.ceil((first+length)/7)*7,selected=rows.filter(r=>M.onDay(r,dayString(C.day)));return `<div class="calendar-month-layout"><section class="calendar-grid-shell" aria-label="${E('월별 달력','Month calendar')}"><div class="calendar-weekdays">${(lang()==='ko'?['일','월','화','수','목','금','토']:['Sun','Mon','Tue','Wed','Thu','Fri','Sat']).map(d=>`<span>${d}</span>`).join('')}</div><div class="calendar-grid">${Array.from({length:cells},(_,i)=>{const day=i-first+1;if(day<1||day>length)return '<span class="calendar-day blank"></span>';const dayRows=rows.filter(r=>M.onDay(r,dayString(day)));return `<button class="calendar-day ${dayString(day)===today?'today':''}" data-calendar-day="${day}" aria-pressed="${day===C.day}" aria-label="${dayString(day)} · ${dayRows.length} ${E('일정','events')}"><span class="calendar-day-number">${day}</span>${dayRows.slice(0,2).map(r=>`<span class="calendar-day-event ${r.status==='cancelled'?'is-cancelled':''}">${esc(r.title)}</span>`).join('')}<span class="calendar-day-dots">${dayRows.slice(0,3).map(r=>`<span class="calendar-dot org-${esc(r.organizations[0])}"></span>`).join('')}</span>${dayRows.length>2?`<small>+${dayRows.length-2}</small>`:''}</button>`;}).join('')}</div></section><aside class="calendar-selected"><div class="eyebrow">${E('선택한 날짜','SELECTED DAY')}</div><h3>${C.month+1}${E('월 ', '/ ')}${C.day}${E('일','')}</h3>${selected.length?selected.map(r=>`<button class="calendar-selected-event" data-event-open="${esc(r.slug)}">${tags(r)}<strong>${esc(r.title)}</strong><small>${esc(timeRange(r))}<br>${esc(r.location)}</small>${r.status!=='published'?`<small>${statusName(r.status)}</small>`:''}</button>`).join(''):`<p class="calendar-empty-small">${E('등록된 일정이 없어요.','No events on this date.')}</p>`}${canCreate()?button('new',icon('plus','small')+E('이날에 일정 추가','Add on this date')):''}</aside></div>`;}
 function detail(row,{preview=false}={}){const editable=canEdit(row);return `<main class="workspace calendar-workspace calendar-detail">${preview?`<div class="calendar-preview-banner">${E('게시 전 미리보기 · 방문자에게 보일 화면','Preview before publishing · visitor view')}</div>`:`<div class="calendar-back">${button('back',icon('back','small')+E('모든 일정','All events'))}${editable?button('edit',icon('edit','small')+E('수정','Edit')):''}</div>`}<article class="calendar-detail-card"><div>${tags(row)}<span class="calendar-status ${row.status}">${statusName(row.status)}</span></div><h1 class="${row.status==='cancelled'?'is-cancelled':''}">${esc(row.title)}</h1>${row.status==='cancelled'?`<p class="calendar-cancelled-notice">${E('이 일정은 취소되었습니다. 같은 링크에서 변경 사항을 확인할 수 있습니다.','This event has been cancelled. Updates remain available at this link.')}</p>`:''}${row.previewUrl?`<img class="calendar-poster" src="${esc(row.previewUrl)}" alt="${esc(row.title)} ${E('포스터','poster')}">`:row.poster_path?`<div class="calendar-poster-slot" data-event-poster="${esc(row.poster_path)}"><span>${E('포스터를 불러오는 중…','Loading poster…')}</span></div>`:''}<dl class="calendar-facts"><dt>${E('일시','When')}</dt><dd>${esc(dateLabel(row.starts_at))}<br>${esc(timeRange(row))}<small>${E('한국 시간 (UTC+9)','Korea time (UTC+9)')}</small></dd><dt>${E('장소','Where')}</dt><dd>${esc(row.location)}</dd><dt>${E('대상','For')}</dt><dd>${row.organizations.map(label).map(esc).join(' · ')}</dd></dl><p class="calendar-description">${esc(row.description||'')}</p><div class="calendar-detail-actions">${!preview?button('share',icon('link','small')+E('짧은 링크 공유','Share link'),true):''}${!preview&&editable?button(row.status==='cancelled'?'restore':'cancel',row.status==='cancelled'?E('취소 해제','Restore event'):E('일정 취소','Cancel event')):''}${!preview&&editable?button('delete',E('일정 삭제','Delete event'),false,'danger'):''}</div><p class="calendar-updated">${E('마지막 수정','Updated')} · ${esc(dateLabel(row.updated_at||row.starts_at))}</p></article></main>`;}
 function loadingContent(){return `<p class="calendar-loading" role="status">${E('일정을 불러오는 중…','Loading events…')}</p>`;}
 function loading(){return `<main class="workspace calendar-workspace">${loadingContent()}</main>`;}
 function emptyContent(){return `<div class="empty-state calendar-empty">${icon('calendar','large')}<h3>${E('등록된 일정이 없습니다.','No events yet.')}</h3><p>${E('다른 달이나 조직을 선택해 보세요.','Try another month or organization.')}</p></div>`;}
 function errorContent(text){return `<div class="calendar-error" role="alert"><p>${esc(text)}</p>${button('reload',E('다시 불러오기','Try again'))}</div>`;}
 function emptyState(text,back=false){return `<main class="workspace calendar-workspace">${back?button('back',E('일정 목록으로','Back to calendar')):''}${errorContent(text)}</main>`;}
 async function refresh({render:shouldRender=true}={}){
  if(!client())return;const generation=++C.generation,slug=C.slug,userId=me()?.id||null;C.loading=true;C.error='';
  if(shouldRender&&state.view==='calendar')render();
  try{if(slug){const {data,error}=await client().from('together_events').select('*').eq('slug',slug).maybeSingle();if(error)throw error;if(generation!==C.generation||userId!==(me()?.id||null))return;C.current=data;C.missing=!data;}else{const range=M.monthRange(C.year,C.month),rows=[];for(let offset=0;;offset+=200){const {data,error}=await client().from('together_events').select('*').lt('starts_at',range.end).gt('ends_at',range.start).order('starts_at').order('id').range(offset,offset+199);if(error)throw error;rows.push(...data);if(data.length<200)break;}if(generation!==C.generation||userId!==(me()?.id||null))return;C.items=rows;}}
  catch(error){if(generation!==C.generation)return;C.error=message(error);if(slug)C.current=null;}
  finally{if(generation===C.generation){C.loading=false;if(shouldRender&&state.view==='calendar')render();}}
 }
 function showCollection({push=false}={}){revokePosters();C.generation++;C.slug=null;C.current=null;C.error='';state.view='calendar';if(push)history.pushState({},'', '/calendar');void refresh();}
 async function open(slug,{push=false}={}){revokePosters();C.generation++;C.slug=slug;C.current=null;C.error='';state.view='calendar';if(push)history.pushState({},'', '/e/'+encodeURIComponent(slug));await refresh();}
 function suspend(){C.generation++;C.loading=false;}
 function revokePosters(){for(const entry of posters.values())if(entry.url)URL.revokeObjectURL(entry.url);posters.clear();}
 async function afterRender(){for(const slot of $$('#app [data-event-poster], #modal[open] [data-event-poster]')){
  const path=slot.dataset.eventPoster;if(!path)continue;let entry=posters.get(path);
  if(!entry){const userId=me()?.id||null;entry={url:null,error:false};posters.set(path,entry);entry.promise=(async()=>{try{const {data,error}=await client().storage.from(BUCKET).download(path);if(error)throw error;if(!['image/png','image/jpeg','image/webp'].includes(data.type)||data.size>5*1024*1024)throw Error('Invalid image');if(posters.get(path)!==entry||userId!==(me()?.id||null))return;entry.url=URL.createObjectURL(data);}catch{entry.error=true;}})();}
  await entry.promise;if(!slot.isConnected||posters.get(path)!==entry)continue;
  if(entry.url){const img=document.createElement('img');img.className='calendar-poster';img.src=entry.url;img.alt=E('행사 포스터','Event poster');slot.replaceChildren(img);}else{slot.textContent=E('포스터를 불러오지 못했습니다. 일정을 다시 열어 주세요.','The poster could not be loaded. Reopen the event to try again.');if(posters.get(path)===entry)posters.delete(path);}
 }}
 function input(label,id,value,type='text',required=true,max=''){return `<label class="calendar-field">${label}<input id="${id}" type="${type}" value="${esc(value)}" ${required?'required':''} ${max?`maxlength="${max}"`:''}></label>`;}
 function showEditor(row=null){if(!canCreate()||(row&&!canEdit(row))){toast(E('이 일정을 관리할 권한이 없습니다.','You do not have permission to manage this event.'),true);return;}
  const previous=C.editor;
  if(!previous||previous.actor!==me().id||(row?previous.id!==row.id:previous.persisted)){
   if(previous?.previewUrl)URL.revokeObjectURL(previous.previewUrl);
   const date=row?M.dayKey(row.starts_at):dayString(C.day),allowed=window.TogetherAccess.allowedEventOrganizations();
   C.editor={id:row?.id||crypto.randomUUID(),actor:me().id,persisted:!!row,baseVersion:row?.updated_at||null,title:row?.title||'',description:row?.description||'',date,endDate:row?M.dayKey(row.ends_at):date,start:row?M.timeKey(row.starts_at):'14:00',end:row?M.timeKey(row.ends_at):'16:00',location:row?.location||'',organizations:row?.organizations||[allowed[0]],poster_path:row?.poster_path||null,status:row?.status||'draft',posterFile:null,uploadPath:null,uploadComplete:false,removePoster:false,previewUrl:null,error:''};
  }
  editorHTML();
 }
 function editorHTML(){const d=C.editor;if(!d)return;const allowed=window.TogetherAccess.allowedEventOrganizations();showModal(modalHead(d.persisted?E('일정 수정','Edit event'):E('새 일정 등록','New event'),E('내용을 확인한 뒤 게시하세요. 모든 시간은 한국 시간입니다.','Review before publishing. All times use Korea time.'))+`<form id="eventEditorForm" class="modal-body calendar-editor"><div class="calendar-editor-fields">${input(E('행사 제목','Event title'),'eventTitle',d.title,'text',true,160)}<fieldset class="calendar-org-field"><legend>${E('대상 조직 · 여러 개 선택 가능','Organizations · select one or more')}</legend><div>${allowed.map(id=>`<label><input type="checkbox" name="eventOrganization" value="${id}" ${d.organizations.includes(id)?'checked':''}>${esc(label(id))}</label>`).join('')}</div></fieldset><div class="calendar-fields-two">${input(E('시작 날짜','Start date'),'eventDate',d.date,'date')}${input(E('종료 날짜','End date'),'eventEndDate',d.endDate,'date')}</div><div class="calendar-fields-two">${input(E('시작 시간','Start time'),'eventStart',d.start,'time')}${input(E('종료 시간','End time'),'eventEnd',d.end,'time')}</div>${input(E('장소','Location'),'eventLocation',d.location,'text',true,300)}<label class="calendar-field">${E('행사 안내','Event details')}<textarea id="eventDescription" maxlength="5000" placeholder="${E('활동 내용과 준비물을 적어 주세요.','Describe the activities and anything to bring.')}">${esc(d.description)}</textarea></label><label class="calendar-field">${E('홍보 포스터 (선택)','Poster (optional)')}<input id="eventPoster" type="file" accept="image/png,image/jpeg,image/webp"><small>${E('PNG·JPG·WebP, 5 MB 이하','PNG, JPG or WebP, up to 5 MB')}${d.posterFile?' · '+esc(d.posterFile.name):''}</small></label>${d.previewUrl?`<img class="calendar-editor-poster" src="${esc(d.previewUrl)}" alt="${E('포스터 미리보기','Poster preview')}">`:d.poster_path&&!d.removePoster?`<div class="calendar-poster-slot" data-event-poster="${esc(d.poster_path)}"></div>`:''}${d.poster_path||d.posterFile?button('remove-poster',E('포스터 제거','Remove poster')):''}<p class="calendar-editor-note">${E('임시 저장한 일정과 포스터는 담당자만 볼 수 있습니다. 게시하면 누구나 볼 수 있습니다.','Only assigned editors can see draft events and posters. Published events are visible to everyone.')}</p></div><div id="eventEditorError" class="alert error" role="alert" ${d.error?'':'hidden'}>${esc(d.error)}</div><footer class="calendar-editor-footer">${button('save-draft',E('임시 저장','Save draft'))}${button('preview',E('게시 전 미리보기','Preview before publishing'),true)}</footer></form>`,{kind:'event-editor',size:'large'});void afterRender();}
 function capture(){const d=C.editor;if(!d||!$('#eventEditorForm'))return;const field=id=>$('#'+id)?.value||'';d.title=field('eventTitle');d.description=field('eventDescription');d.location=field('eventLocation');d.date=field('eventDate');d.endDate=field('eventEndDate');d.start=field('eventStart');d.end=field('eventEnd');d.organizations=$$('input[name="eventOrganization"]:checked').map(x=>x.value);}
 function validate(){capture();if($('#eventEditorForm')&&!$('#eventEditorForm').reportValidity())return null;try{const data=M.validateDraft(C.editor);if(!canEdit(data))throw Error('organizations');return data;}catch(error){const text=({title:E('행사 제목을 입력해 주세요.','Enter an event title.'),location:E('장소를 입력해 주세요.','Enter a location.'),organizations:E('관리할 수 있는 대상 조직을 선택해 주세요.','Select an organization you can manage.'),time:E('종료 시간이 시작 시간보다 늦어야 합니다.','The end must be later than the start.'),description:E('안내는 5,000자 이내로 적어 주세요.','Keep details under 5,000 characters.')})[error.message]||E('날짜와 시간을 확인해 주세요.','Check the date and time.');editorError(text);return null;}}
 function editorError(text){if(C.editor)C.editor.error=text;const el=$('#eventEditorError');if(el){el.textContent=text;el.hidden=false;}else toast(text,true);}
 function preview(){const data=validate();if(!data)return;const d=C.editor;d.error='';showModal(modalHead(E('게시 전 미리보기','Preview before publishing'))+`<div class="modal-body calendar-preview">${detail({...data,status:'published',poster_path:d.removePoster?null:d.poster_path,previewUrl:d.previewUrl},{preview:true})}<div id="eventEditorError" class="alert error" role="alert" hidden></div></div><footer class="modal-footer">${button('continue-edit',E('계속 수정','Continue editing'))}${button('publish',E('게시하기','Publish'),true)}</footer>`,{kind:'event-preview',size:'large'});void afterRender();}
 function busy(value){C.busy=value;const modal=$('#modal');if(modal&&['event-editor','event-preview'].includes(modalKind))$$('button,input,textarea',modal).forEach(el=>el.disabled=value);}
 function sameFields(row,payload){return Object.keys(payload).every(key=>['starts_at','ends_at'].includes(key)?new Date(row[key]).getTime()===new Date(payload[key]).getTime():JSON.stringify(row[key])===JSON.stringify(payload[key]));}
 async function save(status){if(C.busy||!C.editor)return;const data=validate();if(!data)return;const d=C.editor,actor=d.actor,session=modalSession;
  const active=()=>C.editor===d&&me()?.id===actor&&modalSession===session&&['event-editor','event-preview'].includes(modalKind);
  busy(true);
  try{await window.TogetherAccess.refresh();if(!active())return;if(!canEdit(data))throw {code:'42501'};
   if(!d.persisted){let result=await client().from('together_events').insert({...data,id:d.id,created_by:actor,status:'draft'}).select('*').single();if(result.error?.code==='23505')result=await client().from('together_events').select('*').eq('id',d.id).eq('created_by',actor).single();if(result.error)throw result.error;d.persisted=true;d.baseVersion=result.data.updated_at;if(!active())return;}
   if(!active()||!canEdit(data))return;
   if(d.posterFile&&!d.uploadComplete){if(!d.uploadPath){const ext={'image/png':'png','image/jpeg':'jpg','image/webp':'webp'}[d.posterFile.type];d.uploadPath=`${d.id}/${crypto.randomUUID()}.${ext}`;}const {error}=await client().storage.from(BUCKET).upload(d.uploadPath,d.posterFile,{contentType:d.posterFile.type,upsert:false,cacheControl:'0'});const duplicate=error&&(String(error.statusCode)==='409'||String(error.error||error.message||'').toLowerCase().includes('duplicate'));if(error&&!duplicate)throw error;d.uploadComplete=true;if(!active())return;}
   const poster_path=d.removePoster?null:d.uploadComplete?d.uploadPath:d.poster_path;
   const payload={...data,status,poster_path};let result=await client().from('together_events').update(payload).eq('id',d.id).eq('updated_at',d.baseVersion).select('*').maybeSingle();if(result.error)throw result.error;if(!active())return;
   if(!result.data){const current=await client().from('together_events').select('*').eq('id',d.id).maybeSingle();if(current.error)throw current.error;if(!active())return;if(!current.data||!sameFields(current.data,payload))throw Error('conflict');result=current;}
   const oldPoster=d.poster_path;let cleanupFailed=false;
   if(oldPoster&&oldPoster!==poster_path){const removed=await client().storage.from(BUCKET).remove([oldPoster]);cleanupFailed=!!removed.error;if(!active())return;}
   C.current=result.data;C.items=C.items.filter(e=>e.id!==d.id);C.items.push(result.data);C.editor=null;if(d.previewUrl)URL.revokeObjectURL(d.previewUrl);closeModal(false);revokePosters();
   toast(status==='draft'?E('임시 저장했습니다. 담당자만 볼 수 있습니다.','Draft saved. Only assigned editors can see it.'):E('일정을 게시했습니다. 공유 링크로 바로 볼 수 있습니다.','Event published. Anyone can open its shared link.'));
   if(cleanupFailed)toast(E('일정은 저장됐지만 이전 포스터 파일 정리가 완료되지 않았습니다.','The event was saved, but cleanup of its previous poster did not complete.'),true);
   window.TogetherNavigation.openEvent(result.data.slug);
  }catch(error){if(active())editorError(message(error));}finally{busy(false);}
 }
 async function changeStatus(status){const row=C.current;if(C.busy||!row||!canEdit(row))return;if(status==='cancelled'&&!confirm(E('이 일정을 취소된 일정으로 표시할까요?','Mark this event as cancelled?')))return;const actor=me()?.id,active=()=>me()?.id===actor&&C.current?.id===row.id;C.busy=true;try{const {data,error}=await client().from('together_events').update({status}).eq('id',row.id).eq('updated_at',row.updated_at).select('*').maybeSingle();if(error)throw error;if(!data)throw Error('conflict');if(!active())return;C.current=data;render();toast(status==='cancelled'?E('일정에 취소 표시를 했습니다.','The event is marked cancelled.'):E('취소 표시를 해제했습니다.','The event is restored.'));}catch(error){if(active())toast(message(error),true);}finally{C.busy=false;}}
 async function removeEvent(){const row=C.current;if(C.busy||!row||!canEdit(row)||!confirm(E('이 일정과 포스터를 삭제할까요?','Delete this event and its poster?')))return;const actor=me()?.id,active=()=>me()?.id===actor&&C.current?.id===row.id;C.busy=true;try{
   const hidden=await client().from('together_events').update({status:'draft'}).eq('id',row.id).eq('updated_at',row.updated_at).select('*').maybeSingle();if(hidden.error)throw hidden.error;if(!hidden.data)throw Error('conflict');if(!active())return;C.current=hidden.data;
   if(hidden.data.poster_path){const removed=await client().storage.from(BUCKET).remove([hidden.data.poster_path]);if(removed.error)throw removed.error;if(!active())return;}
   const {data,error}=await client().from('together_events').delete().eq('id',row.id).eq('updated_at',hidden.data.updated_at).select('id');if(error)throw error;if(!data.length)throw Error('conflict');if(!active())return;
   C.items=C.items.filter(e=>e.id!==row.id);C.current=null;revokePosters();toast(E('일정을 삭제했습니다.','Event deleted.'));window.TogetherNavigation.navigate('calendar');
  }catch(error){if(active()){render();toast(message(error),true);}}finally{C.busy=false;}}
 document.addEventListener('click',event=>{
  const opened=event.target.closest('[data-event-open]');if(opened){window.TogetherNavigation.openEvent(opened.dataset.eventOpen);return;}
  const org=event.target.closest('[data-calendar-org]');if(org){const id=org.dataset.calendarOrg;if(id==='all-organizations')C.organizations=[];else C.organizations=C.organizations.includes(id)?C.organizations.filter(o=>o!==id):[...C.organizations,id];preferences();render();return;}
  const layout=event.target.closest('[data-calendar-layout]');if(layout){C.layout=layout.dataset.calendarLayout;preferences();render();return;}
  const day=event.target.closest('[data-calendar-day]');if(day){C.day=Number(day.dataset.calendarDay);render();return;}
  const action=event.target.closest('[data-calendar-action]')?.dataset.calendarAction;if(!action||C.busy)return;
  if(action==='new')showEditor();else if(action==='edit')showEditor(C.current);else if(action==='preview')preview();else if(action==='continue-edit')editorHTML();else if(action==='save-draft')void save('draft');else if(action==='publish')void save('published');else if(action==='cancel')void changeStatus('cancelled');else if(action==='restore')void changeStatus('published');else if(action==='delete')void removeEvent();else if(action==='back')window.TogetherNavigation.navigate('calendar');else if(action==='reload')void refresh();else if(action==='share'&&C.current)window.TogetherNavigation.share(C.current.title,'/e/'+C.current.slug);else if(action==='remove-poster'&&C.editor){capture();const d=C.editor;d.posterFile=null;d.uploadComplete=false;d.removePoster=true;if(d.previewUrl)URL.revokeObjectURL(d.previewUrl);d.previewUrl=null;editorHTML();}else if(['previous','next','today'].includes(action)){if(action==='today'){const now=M.dayKey(new Date());C.year=Number(now.slice(0,4));C.month=Number(now.slice(5,7))-1;C.day=Number(now.slice(-2));}else{const date=new Date(C.year,C.month+(action==='next'?1:-1),1);C.year=date.getFullYear();C.month=date.getMonth();C.day=1;}void refresh();}
 });
 document.addEventListener('change',event=>{if(event.target.id==='calendarIncludeAll'){C.includeAll=event.target.checked;preferences();render();return;}if(event.target.closest('#eventEditorForm'))capture();if(event.target.id==='eventPoster'&&C.editor){const file=event.target.files?.[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>5*1024*1024){editorError(E('5 MB 이하 PNG·JPG·WebP 이미지를 선택해 주세요.','Choose a PNG, JPG or WebP image up to 5 MB.'));event.target.value='';return;}const d=C.editor;if(d.previewUrl)URL.revokeObjectURL(d.previewUrl);d.posterFile=file;d.previewUrl=URL.createObjectURL(file);d.removePoster=false;d.uploadPath=null;d.uploadComplete=false;d.error='';editorHTML();}});
 document.addEventListener('input',event=>{if(event.target.id==='calendarSearch'){C.query=event.target.value;const position=event.target.selectionStart;render();const input=$('#calendarSearch');input?.focus({preventScroll:true});if(input?.type!=='search')input?.setSelectionRange(position,position);}else if(event.target.closest('#eventEditorForm'))capture();});
 document.addEventListener('submit',event=>{if(event.target.id==='eventEditorForm'){event.preventDefault();preview();}});
 document.addEventListener('together:identity',()=>{const next=me()?.id||null;if(next===identity)return;identity=next;suspend();C.items=[];C.current=null;revokePosters();if(C.editor?.previewUrl)URL.revokeObjectURL(C.editor.previewUrl);C.editor=null;if(['event-editor','event-preview'].includes(modalKind))closeModal(false);});
 document.addEventListener('together:access',()=>{C.items=C.items.filter(visible);if(C.current&&!visible(C.current))C.current=null;if(C.editor&&(!canCreate()||C.editor.actor!==me()?.id)){C.editor=null;if(['event-editor','event-preview'].includes(modalKind))closeModal(false);}if(state.view==='calendar')void refresh();});
})();
