'use strict';
const beforeDashboardNav=navEntries;
navEntries=function(){return [['dashboard','book',E('주별 공과','Weekly lessons')],...beforeDashboardNav()];};
let dashboardQuery='';
function dashboardHTML(){
 const list=lessons().filter(l=>Object.values(l.title).join(' ').concat(' ',Object.values(l.date||{}).join(' ')).toLowerCase().includes(dashboardQuery.toLowerCase()));
 const all=lessons(),selected=currentLesson();
 return `<main class="workspace dashboard"><div class="dashboard-hero"><div><div class="eyebrow">COME, FOLLOW ME</div><h1>${E('한 주의 말씀,<br>함께 나누는 생각.','A week of study.<br>A thought to share.')}</h1><p>${E('공과를 고르고, 마음에 남는 말씀을 읽고 기록해 보세요.','Choose a lesson, find a passage that stays with you, and reflect.')}</p><button class="btn primary" data-week="${esc(lessonKey(selected))}">${E('이어서 공부하기','Continue studying')}${icon('arrow')}</button></div><div class="dashboard-quote">${icon('book','large')}<span>${E('배우고 · 기록하고 · 나누다','LEARN · REFLECT · SHARE')}</span><strong>${esc(selected.title[lang()]||selected.title.ko)}</strong><small>${esc(selected.date?.[lang()]||selected.date?.ko||'')}</small></div></div><div class="dashboard-section"><div><div class="eyebrow">YOUR WEEKLY STUDY</div><h2>${E('주별 공과 모아보기','Explore weekly lessons')}</h2><p>${E('등록된 공과를 날짜별 카드에서 열어 보세요.','Open an available lesson from its weekly card.')}</p></div><label class="week-search">${icon('search')}<input id="weekSearch" type="search" value="${esc(dashboardQuery)}" placeholder="${E('제목 또는 날짜 검색','Search by title or date')}" aria-label="${E('주별 공과 검색','Search weekly lessons')}"></label></div><div id="weeklyCards" class="week-grid">${weeklyCardsHTML(list)}</div><div class="dashboard-note">${icon('info','small')}<p>${E(`현재 학습 본문이 등록된 공과는 ${all.length}개입니다. 새로운 공과를 등록하면 카드가 자동으로 추가됩니다.`,`There ${all.length===1?'is':'are'} ${all.length} available lesson${all.length===1?'':'s'}. New lessons appear here when their content is added.`)}</p></div></main>`;
}
function weeklyCardsHTML(list){return list.map((l,i)=>{
 const key=lessonKey(l),week=l.id.match(/(?:cfm-)?(20\d{2})-(\d{1,2})$/),count=state.notes.filter(n=>n.scope==='class'&&n.anchor.lessonKey===key&&(!cloud.enabled||n.remote)).length;
 return `<button class="week-card" data-week="${esc(key)}"><div class="week-card-cover tone-${i%3}"><span>${week?'WEEK '+week[2].padStart(2,'0'):E('공과','LESSON')}</span>${icon('book','large')}<small>${week?week[1]:'COME, FOLLOW ME'}</small></div><div class="week-card-content"><div class="week-card-date">${esc(l.date?.[lang()]||l.date?.ko||E('추가한 공과','Added lesson'))}</div><h3>${esc(l.title[lang()]||l.title.ko)}</h3><p>${l===BASE?E('잠언 · 전도서','Proverbs · Ecclesiastes'):E('읽기 자료와 연결된 인사이트','Reading and linked reflections')}</p><div class="week-card-footer"><span>${icon('chat','small')}${count} ${E('개의 나눔','reflections')}</span><strong>${E('공부하기','Open lesson')}${icon('arrow','small')}</strong></div></div></button>`;
 }).join('')+`<button class="week-card add-week" data-nav="import">${icon('plus','large')}<strong>${E('새 공과 등록','Add a lesson')}</strong><span>${E('다음 주의 공부를 준비해 보세요.','Prepare another week of study.')}</span></button>`;}
document.addEventListener('click',event=>{const el=event.target.closest('[data-week]');if(!el)return;const lesson=lessons().find(l=>lessonKey(l)===el.dataset.week);if(!lesson)return;state.activeLesson=lessonKey(lesson);state.filters={query:'',type:'all',lang:'all',section:'all'};currentSection='intro';navigate('read');});
document.addEventListener('input',event=>{if(event.target.id!=='weekSearch')return;dashboardQuery=event.target.value;$('#weeklyCards').innerHTML=weeklyCardsHTML(lessons().filter(l=>Object.values(l.title).join(' ').concat(' ',Object.values(l.date||{}).join(' ')).toLowerCase().includes(dashboardQuery.toLowerCase())));});
// The dashboard is the landing page on every visit. Choosing a card opens the reader.
state.view='dashboard';render();
